'''
On Day-4.py File :Day-5 Changes,
    -> SOUND GENERATOR,
    -> INSIDE PLAYER CLASS : FRAME ANIMATION,
    -> NEW GAME STAT : MENU,
    -> MUTE-UNMUTE OPTION,
    -> RESET GAME FUNCTION,
    -> OTHER SMALL CHANGES...
'''